-- MySQL Script generated by MySQL Workbench
-- Tue Oct 30 21:09:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fotodeteccionesbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fotodeteccionesbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fotodeteccionesbd` DEFAULT CHARACTER SET utf8 ;
USE `fotodeteccionesbd` ;

-- -----------------------------------------------------
-- Table `fotodeteccionesbd`.`Vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fotodeteccionesbd`.`Vehiculos` (
  `placa` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`placa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fotodeteccionesbd`.`Lugares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fotodeteccionesbd`.`Lugares` (
  `idLugares` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLugares`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fotodeteccionesbd`.`Fotodetecciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fotodeteccionesbd`.`Fotodetecciones` (
  `idFotodetecciones` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL,
  `velocidad` DOUBLE NOT NULL,
  `Vehiculos_placa` VARCHAR(6) NOT NULL,
  `Lugares_idLugares` INT NOT NULL,
  PRIMARY KEY (`idFotodetecciones`, `Vehiculos_placa`, `Lugares_idLugares`),
  INDEX `fk_Fotodetecciones_Vehiculos_idx` (`Vehiculos_placa` ASC),
  INDEX `fk_Fotodetecciones_Lugares1_idx` (`Lugares_idLugares` ASC),
  CONSTRAINT `fk_Fotodetecciones_Vehiculos`
    FOREIGN KEY (`Vehiculos_placa`)
    REFERENCES `fotodeteccionesbd`.`Vehiculos` (`placa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fotodetecciones_Lugares1`
    FOREIGN KEY (`Lugares_idLugares`)
    REFERENCES `fotodeteccionesbd`.`Lugares` (`idLugares`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
